spryk: structure
description: "Adds a new *module* structure."
priority: 1
mode: both

arguments:
    organization:
        inherit: true
        default: SprykerShop

    module:
        inherit: true
        type: NewModuleType

    theme:
        inherit: true
        default: default

    template:
        value: Yves/Theme/YvesTwigTemplate.twig.twig

    targetFilename:
        value: "{{ module }}Config.php"

    targetPath:
        value: "{{ module }}/src/{{ organization }}/Yves/{{ module }}/Theme/"

postSpryks:
    - AddModule
