spryk: template
description: "Adds a new *Module*GlueDependencyProvider to the Glue application."

arguments:
  module: ~

  organization:
    default: Spryker

  template:
    value: Glue/GlueDependencyProvider.php.twig

  targetFilename:
    value: "{{ module }}DependencyProvider.php"

  targetPath:
    default: "{{ module }}/src/{{ organization }}/Glue/{{ module }}/"

preSpryks:
  - CreateSprykerModule
