spryk: template
description: "Adds a new *module*Config to the Glue application."

arguments:
  module: ~

  organization:
    default: Spryker

  template:
    value: Glue/GlueConfig.php.twig

  targetFilename:
    value: "{{ module }}Config.php"

  targetPath:
    default: "{{ module }}/src/{{ organization }}/Glue/{{ module }}/"

preSpryks:
  - CreateSprykerModule
